#!/bin/bash

if [[ "$1" = "" ]]; then
    echo "Usage: openurl {hidden}"
    echo
    echo "Note: This file only for Ghost Framework, if you execute it without"
    echo "Ghost Framework it will not work, this is only a part of main code."
    exit
fi

if [[ "$1" == *"http"* ]]; then
  {
  adb shell "am start -a android.intent.action.VIEW -d $1"
  } &>/dev/null
else
  {
  adb shell "am start -a android.intent.action.VIEW -d https://${1}"
  } &>/dev/null
fi
