#!/usr/bin/bash

if [[ "$1" = "" ]]; then
    echo "Usage: screen {hidden}"
    echo
    echo "Note: This file only for Ghost Framework, if you execute it without"
    echo "Ghost Framework it will not work, this is only a part of main code."
    exit
fi

{
scrcpy
} &>/dev/null
